version: "3.8"
services:
  vault:
    image: vault
    ports:
      - 8200:8200
    volumes:
      - ./init.sh:/data/init.sh
#    command: TODO: implement
    environment:
      - --cap-add=IPC_LOCK
      - VAULT_DEV_ROOT_TOKEN_ID=demo
