version: "3.8"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./init.sh:/data/init.sh
    command: sh -c "redis-server --daemonize yes && sleep 5 && /data/init.sh && tail -f /dev/null"